### ISSUE TITLE
Creating new crop of the same image doesn't remove old crop from cache

### ISSUE THREAD

**Issue by ghost** [horst-n/CroppableImage3#1]
We've found with a couple of websites that when you go back into an already cropped image and set a new crop - the old crop remains in cache. 

This then results in the old crop being served up. 

To recreate:

1) Set a new crop settings in the field settings. E.g "crop_image,1440,300,template_name"
2) Upload an image and crop
3) Go to the page in question on the front-end
4) Go back to that page's admin screen and set a new crop
5) See that it hasn't changed on the front-end

**Comment by horst-n** [comment]
I believe you get tricked with browser caching.
Please check the new and old varition files directly via console / ftp!
