### ISSUE TITLE
CI3 incompatible with PHP 7.4

### ISSUE THREAD

**Issue by matjazpotocnik** [horst-n/CroppableImage3#10]
Deprecated: Array and string offset access syntax with curly braces is deprecated in C:\inetpub\wwwroot\site\modules\CroppableImage3\classes\CroppableImage3Helpers.class.php on line 280, 281 and 284

https://wiki.php.net/rfc/deprecate_curly_braces_array_access

**Comment by horst-n** [comment]
should be fixed for some time now
