### ISSUE TITLE
Issue with switching from standard image field

### ISSUE THREAD

**Issue by gerritvanaaken** [horst-n/CroppableImage3#3]
I have a running website with standard image fields, which I want to switch to CroppableImage3. 

Problem is, I use the module "Image Extra" http://modules.processwire.com/modules/image-extra/ This provides some custom extra columns in the database. see here:

<img width="720" alt="bildschirmfoto 2016-12-23 um 10 56 32" src="https://cloud.githubusercontent.com/assets/227735/21451312/82f73f64-c8fe-11e6-8073-bf61534a91a9.png">

When I’m switching this field to CroppableImage3, the extra columns in the database are gone. Not cool, although I understand why, of course. Is there a chance that you keep all unknown extra columns in the database when changing the field type from image to croppableimage?

Happy X-Mas and keep up the good work!

**Comment by horst-n** [comment]
Hi @gerritvanaaken 
I'm sorry, but I don't have enough knowledge of how the Image Extra module attaches the data to the (core) image fields. I think there will be a hacky solution like keeping a backup dump of all image extra values, switch the imagefield to CAI3 and then reassign the image extra records. (on mysql level).
But we should ask / ping @justb3a - maybe she knows a workaround, or even better (!!) maybe she knows a way how to implement support for imagefield changing into the image extra module.

Croppableimage3 is only extending the core image field. There is nothing special with hooking done. Image Extra has much more to hook, I believe. So, there is a real chance that Bea knows something. :)

**Comment by gerritvanaaken** [comment]
Nevermind, I can manually backup and restore this database table once. Shouldn’t be a problem. And in 2017 we well have a core method for adding custom fields to images anyway.
