### ISSUE TITLE
Wrong filename on thumbnail if crop setting contains Uppercase letter

### ISSUE THREAD

**Issue by OvidiuS** [horst-n/CroppableImage3#5]
**CroppableImage3 version: 0.9.17
Processwire version: 3.0.42**

If I name my crop setting in camel case: `cropSetting,600,600` then the thumbnail that gets generated for the 600x600 size when i upload an image will have a name that ends with "....cropSetting.jpg"

This creates an invalid URL in the front-end, because this: 
`$page->mycroppableImagefield->getCrop('cropSetting')->url` 
outputs an URL ending with "....cropsetting.jpg" (all lowercase), while the actual file still has an Uppercase in its name.

If I go back and manually select the area to crop for that file on the "cropSetting" setting, then **another** file variation gets generated, this time ending with "....cropsetting.jpg" (all lowercase) and the URL will finally work.

**Comment by horst-n** [comment]
There were issues with lowercase versus MixedCase in the past. I thought all were fixed. I need to investigate and check again. (But have no time ATM)

**Comment by horst-n** [comment]
I think this was due to a not updated version of the module. So can be closed now.
