### ISSUE TITLE
InputfieldCroppableImage3 benötigt FieldtypeCroppableImage2

### ISSUE THREAD

**Issue by tbba** [horst-n/CroppableImage3#6]
I have the latest PW3 dev and CroppableImage 3 and see a warning:

 Fehlerhafte Modul-Abhängigkeit: InputfieldCroppableImage3 benötigt FieldtypeCroppableImage2

**Comment by horst-n** [comment]
Hi Carl (@tbba),

sorry for that, it was a bug while trying to solve the recognition issue with the PW upgrade system. I had changed this allready 1 or 2 days ago. You need to manually install the latest version 1.1.5!

see also: https://processwire.com/talk/topic/14090-croppable-image-3/?page=6#comment-145213

**Comment by tbba** [comment]
yes it appears to be fixed. Thank you!!!
